Added workflow for Security file check (#91)

diff --git a/.github/workflows/onpullrequest.yml b/.github/workflows/onpullrequest.yml
--- a/.github/workflows/onpullrequest.yml
+++ b/.github/workflows/onpullrequest.yml
@@ -4,23 +4,36 @@ on:
   pull_request:
 
 jobs:
+
+  security-file-check:
+    runs-on: [ ubuntu-20.04 ]
+    steps:
+      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
+        with:
+          fetch-depth: 0
+
+      - name: Check Security.md file
+        run: |
+          if [ ! -f ./SECURITY.md ]; then
+            echo "Security.md file is missing"
+            exit 1
+          fi
+          
   build-test-scan:
     runs-on: [ ubuntu-20.04 ]
+    needs: [ "security-file-check" ]
     env:
       http_proxy: ${{ secrets.HTTP_PROXY }}
       https_proxy: ${{ secrets.HTTPS_PROXY }}
       no_proxy: ${{ secrets.NO_PROXY }}
       PYTHONPATH: ${{ github.workspace }}:$PYTHONPATH
     steps:
-      - uses: actions/checkout@v3
-        with:
-          fetch-depth: 0
 
       #- name: python linter TODO: Check if innersource provides aby linter.
        # uses: psf/black@stable
 
       - name: Setup Python
-        uses: actions/setup-python@v4
+        uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236 # v4.7.1
         with:
           python-version: '3.8.10'
           
